language: php
php:
- '7.2'
- nightly

install:
- travis_retry composer self-update && composer --version
- export PATH="$HOME/.composer/vendor/bin:$PATH"


before_script:
- wget https://phar.phpunit.de/phpunit-7.2.7.phar
- chmod +x phpunit-7.2.7.phar
- sudo mv phpunit-7.2.7.phar /usr/local/bin/phpunit
- /usr/local/bin/phpunit --version
- composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

script:
- /usr/local/bin/phpunit --verbose $PHPUNIT_FLAGS