language: php

php:
- '7.2'
- nightly

before_install:
- composer require phpunit/phpunit:7.4.* satooshi/php-coveralls:dev-master
- composer install --dev

script:
- ./vendor/bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
- php vendor/bin/coveralls -v

after_success:
  - bash <(curl -s https://codecov.io/bash)