language: php

php:
- '7.2'
- nightly

install:
- composer require phpunit/phpunit:7.4.*
- composer install --dev

script:
- ./vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)